// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzprqowpjbvrcqtpwfer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cHJxb3dwamJ2cmNxdHB3ZmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTM1MDMsImV4cCI6MjA2OTE4OTUwM30.RQ6VSsEQdt7R0b-5v1ARqC621zGvmgobvki56Ddw63g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});